# train_ebmpc.yaml
defaults:
  - _self_

ckpt_base_path: ./
world_model_path: outputs/2025-09-21/05-22-44

training:
  seed: 33
  epochs: 100
  batch_size: 16
  num_workers: 12
  lr: 0.0001
  gradient_clip_val: 1.0
  log_every_n_steps: 10
  val_check_interval: 1.0
  save_every_n_epochs: 1
  use_wandb: true

model:
  num_mcmc_steps: 2
  mcmc_step_size: 3000
  mcmc_step_size_learnable: true
  
  embedding_dim: 384
  num_transformer_blocks: 6
  multiheaded_attention_heads: 6
  ffn_dim_multiplier: 1